
name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main", "maven_buildsystem", "grafikus" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn -B package --file drukmakor/pom.xml

   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify --file drukmakor/pom.xml
    - run: mkdir drukmakor/staging && cp drukmakor/target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging